name: WarnXS
main: de.erethon.warnxs.WarnXS
version: ${project.version}${buildNo}
author: Daniel Saukel
description: ${project.description}
website: ${project.url}
commands:
  warnxs:
    description: Reference command for WarnXS.
    aliases: [w,wxs,warn]
